### ISSUE TITLE
Budget source expenditure at zero

### ISSUE THREAD

**Issue by smit1678** [undp/undp.github.com#130]
Budget source expenditure is at zero currently. Flagged in #42, making a separate ticket here. Example source: http://open.undp.org/#2014/filter/donors-00253. 

![](https://cloud.githubusercontent.com/assets/3297817/5320274/7bf12456-7c7e-11e4-9118-5504ae879940.png)

cc @kamicut

**Comment by kamicut** [comment]
@smit1678 I am not seeing this on my machine. Is this bug still showing for you?

**Comment by kamicut** [comment]
Issue is resolved

![undp_projects](https://cloud.githubusercontent.com/assets/719357/5784876/92bebb76-9d9e-11e4-86b9-1a8517912a72.png)
