### ISSUE TITLE
Link to map view with budget source links on project page

### ISSUE THREAD

**Issue by smit1678** [undp/undp.github.com#131]
Budget Source links on project pages link to List view when clicking on a donor. Should link to map view by default. 

To replicate: 

1. From [project page](http://open.undp.org/#project/00061104), click on USA under Budget Sources
2. List view then shows at this view: http://open.undp.org/#2014/filter/donors-00253

cc @kamicut

**Comment by kamicut** [comment]
This is no longer an issue
