### ISSUE TITLE
Add contracts info to the individual projects

### ISSUE THREAD

**Issue by Jura** [undp/undp.github.com#141]
Project profiles should be able to display information about related contracts (POs, vendors, etc).

**Comment by Jura** [comment]
Data example:

AWARD_ID,VENDOR_ID,VENDOR_NAME,PO_ID,PO_DESCRIPTION,PO_DATE,PO AMOUNT (USD)
47111,618,test,17296,E) Network data service units,1/22/13,10520
58898,2863,test,17303,E) Air Tickets - International,1/23/13,7749
61104,3915,test,17321,S) Mobile communications servi,1/29/13,6916.43
58922,2829,test,17328,E) Uninterruptible power supply,1/29/13,6344
58898,10142,test,17352,G) Fuel for vehicles,2/4/13,29103.61
58936,13279,test,17362,E) Software (license),2/5/13,7576.56
58936,13279,test,17362,E) Software (license),2/5/13,9729.48

**Comment by Jura** [comment]
It's been resolved in https://github.com/Jura/undp.github.com (develop branch), waiting for final confirmation

**Comment by Jura** [comment]
@abdulriza, where we are with this feature?

**Comment by abdulriza** [comment]
@Jura we have shared the mock-up and details with Procurement Services Unit for feedback and confirmation on the specification. We are still waiting for their response to finalize.

**Comment by Jura** [comment]
@abdulriza Last time you said it would be better to not mentioning line description for the contracts if there is no PO description - to leave it empty. I checked both version on a random project and version with line descriptions used if there is no PO description looks like that: 

![open-line-descriptions](https://cloud.githubusercontent.com/assets/417604/9614881/9dbee2da-50c2-11e5-9d1e-183e37675760.png)

If we stick to the PO reference only we will end up with something like that:

![open-po-descriptions](https://cloud.githubusercontent.com/assets/417604/9614899/b3c1e1fe-50c2-11e5-8b54-ffb08dd3fd20.png)

I fully understand your concern but still think that having cells filled looks better. What do you think?

**Comment by abdulriza** [comment]
@Jura I totally agree with you. This example looks better and make sense to use line details. But last time when I checked few examples looked bad. Let me check once again and discuss with you. Thanks

**Comment by Jura** [comment]
I guess both versions are not perfect. But I would rather avoid empty cells if possible...

**Comment by Jura** [comment]
@abdulriza , as agreed, I changed the logic for PO descriptions and used generic placeholder "Purchase of goods/services" for records without proper PO reference provided. Changes committed to the https://github.com/Jura/undp.github.com/tree/develop

**Comment by Jura** [comment]
@abdulriza I updated project profile code to show line description for one line POs (if po reference is not provided) and updated data file. Check it at https://github.com/Jura/undp.github.com/tree/develop
