### ISSUE TITLE
Remove 2010 and 2011 data 

### ISSUE THREAD

**Issue by abdulriza** [undp/undp.github.com#153]
@Jura As we discussed, the portal is currently showing inconsistent budget and expenditure details for the year 2010 and 2011. This is due to the reason that current xml capture historical data from 2012 only. Since we don't have a proper solution to bring in the required 2010 & 2011 data, it would be good to avoid showing the wrong numbers on portal. Therefore, we need to remove 2010 and 2011 and limit the year filter only from 2012.

Thanks,
Riza

**Comment by Jura** [comment]
@abdulriza , how do you want to approach this? Just removing respective xml files and reparsing data doesn't work - for example 2012 file contains plenty of activities which started and finishes in earlier years, hence system is including those years into index. Shall I just hardcode that only 2012 and later years shall be taken into account? I'm not 100% percent sure about calculations in that case...
