### ISSUE TITLE
Theme filter shows empty categories

### ISSUE THREAD

**Issue by Jura** [undp/undp.github.com#158]
Categories without projects still displayed as <1% items
http://open.undp.org/#2015/filter/operating_unit-IRN

**Comment by Jura** [comment]
@abdulriza, I updated https://github.com/Jura/undp.github.com/tree/master so chart won't display zero budget topics, please review and let me know if we can go to production

**Comment by abdulriza** [comment]
@Jura Looking good. You can go ahead with production. Thanks.

**Comment by Jura** [comment]
Done, changes should be in production shortly. Just a side note - please don't close issues until I actually merge changes to master branch and update actual site. Then, after verification, I'll close ticket myself.
