### ISSUE TITLE
Arranging documents in order on project pages

### ISSUE THREAD

**Issue by abdulriza** [undp/undp.github.com#159]
@Jura The documents listed on project pages need to be arranged giving priority to prodocs and results documents in the top.
- any document with a tag A02 or A03 or A04 or A05 in the top
- After in the order of A01, A07, A08 and A09
- Any documents with A 10 in the last 

in the order of 
![image](https://cloud.githubusercontent.com/assets/3297817/9231106/57b6d37a-40f4-11e5-8940-815775ef6b27.png)

**Comment by Jura** [comment]
@abdulriza, do you have a specific example of project where order of documents is obviously wrong? I fixed scripts but need to test whether they work as expected and most of the projects I checked show docs in a proper way already

**Comment by abdulriza** [comment]
@Jura you can check 00050123 the document '00050123_project Document PAL 1000063805' should appear before progress report.

**Comment by Jura** [comment]
Done. I submitted changes (including reparsed data files) into https://github.com/Jura/undp.github.com/tree/master, check locally and let me know if I can pull it to prod

**Comment by abdulriza** [comment]
@Jura Checked. Looks good. You can go ahead with prod. Thanks.

**Comment by Jura** [comment]
Fixed, changes will be in Production in a few minutes
