### ISSUE TITLE
Top recipient Offices list - showing empty list under International resources

### ISSUE THREAD

**Issue by abdulriza** [undp/undp.github.com#162]
@Jura currently we are showing two tabs (international resources and national resources) and the countries are picked according to the predefined country category list. For example; when we select the filter for 'Brazil' in country office the top recipient country Brazil will appear under natural resources tab. Since it appears by default with international resources tab, this field is shown empty under international resources and one has to click the the national resources tab to see the list. 

Can we apply the logic to show the correct tab by default when one there is no country listed under international resources? In this example, when we select Brazil the top recipient receipt offices will show the national resources tab instead of international resources empty one.

**Comment by Jura** [comment]
Fixed
