### ISSUE TITLE
Remove cycling links on the project profile page (documents section)

### ISSUE THREAD

**Issue by Jura** [undp/undp.github.com#172]
With the last update we have added the links of project pages from open.undp.org as contract summary document (purchase order information) in xml. Now this link is shown as a document in open.undp.org. I would appreciate if you could make the code changes in order to avoid including this in the document list;

![openundporg-project-documents-cycling](https://cloud.githubusercontent.com/assets/417604/10620490/5ca3745c-7749-11e5-9161-5eaa40b07f11.png)

The easy option will be to omit document category “A11” in the list but it will also take out other summary documents CO have uploaded. Basically we do not want to include any links with open.undp.org in document list. Following is an example to show how it is published in xml;

`<document-link url="http://open.undp.org/#project/00043217" format="application/pdf"><title>Purchase Order Summary</title><language code="en"/><category code="A11"/></document-link>`

**Comment by Jura** [comment]
@abdulriza check https://github.com/Jura/undp.github.com for the fix

**Comment by abdulriza** [comment]
@Jura Looks good. You can go ahead and push it live. 

Thanks.

**Comment by Jura** [comment]
@abdulriza I've updated production site, please check in 10-15 minutes and close this ticket if everything is ok

**Comment by abdulriza** [comment]
@Jura Looks perfect. Thanks
