### ISSUE TITLE
Enable project pictures slideshow for the project profile template

### ISSUE THREAD

**Issue by Jura** [undp/undp.github.com#182]

**Comment by Jura** [comment]
@abdulriza, can you give me an example of project which provides images to display?

**Comment by Jura** [comment]
@abdulriza - check it locally before I merge changes to Production, repo: https://github.com/Jura/undp.github.com/tree/master
Check project 00061754

**Comment by abdulriza** [comment]
@Jura I checked few more projects and they are also looking good. What do you think if we make the vertical frame size also static? Just thinking, some pictures are taking lot of space, for example, like the 3rd picture in the above example!

**Comment by Jura** [comment]
@abdulriza - we cannot control size of the pictures people are linking to the project, there always will be items with different size, orientation, aspect ratio and we can't just crop them arbitrarily (i.e. make height static)... I would say we will keep it up to users letting them know that we prefer pictures of the same dimensions, not less than 780px wide and too much bigger than that number as well

**Comment by abdulriza** [comment]
@Jura Agree. We are good to go then. Thanks.
