### ISSUE TITLE
Funding by country filter list doesn't show complete country list

### ISSUE THREAD

**Issue by abdulriza** [undp/undp.github.com#195]
@Jura many of the countries (mostly main donors) are not available under the 'funding by country' filter list. Eg. Japan, USA, Norway.... If i try to use the direct url to the missing country (eg. http://open.undp.org/#2016/filter/donor_countries-JPN) it appears as zero projects in the list. 

![global](https://cloud.githubusercontent.com/assets/3297817/14676069/eb0dd0f0-06d9-11e6-9b8e-976302702c55.png)

![japan](https://cloud.githubusercontent.com/assets/3297817/14676073/edd7c34a-06d9-11e6-9bd9-9ff8b706e723.png)

**Comment by Jura** [comment]
Ok, I'll check what's going on

**Comment by Jura** [comment]
@abdulriza - portal has been updated, please check

**Comment by abdulriza** [comment]
@Jura Looks good. Thanks.
