### ISSUE TITLE
New XML format: divide expense into expenditure and disburesment

### ISSUE THREAD

**Issue by Jura** [undp/undp.github.com#199]
Hi Jura,

From May we will start publishing disbursement element in our current XML and this will require code changes for portal update. Following is the new xml format;

https://www.dropbox.com/sh/kvy7lopqrasvnis/AAAwq091C2-8dY8OkSdWLdXTa?dl=0

Currently we publish expense in the element  <transaction-type code="4" /> in hierarchy 2. In the new xml, the expense amount will be split into expense and disbursements. 

```
            <transaction-type code="4" /> - expense
            <transaction-type code="3" /> - disbursement
```

In the portal we currently publish expense only. With this change we can either bring in disbursement field to the visualization or simply change the calculation to include it to the expense with the code.

Option 1: In addition to expense we can show disbursements. I guess, relatively this will be more complicated as we need to add disbursement in multiple places and discuss how we would want to show on the global page.

Option 2: Instead we can change the calculation in getting the expenses at project and global pages by bringing in disbursement. With this option we will add <transaction-type code="3" /> to <transaction-type code="4" /> in deriving the expense amounts. 

Let’s discuss once you see this mail. 

Thanks,
Riza

**Comment by Jura** [comment]
Option 2: fixed

@abdulriza - you can test code in https://github.com/Jura/undp.github.com/tree/feature/issue-199 - it should produce identical results with what we have now on open.undp.org but new file format is used. I'll continue working on implementation of better visualization for expenditures/disbursements next week

**Comment by abdulriza** [comment]
@Jura thanks. I will get it tested.

**Comment by Jura** [comment]
I'm going to split this ticket, this one remains for Option 2 and Option 1 goes to #200

**Comment by Jura** [comment]
Closing due to the complete portal rewrite
