### ISSUE TITLE
Portal update and include 2017

### ISSUE THREAD

**Issue by abdulriza** [undp/undp.github.com#209]
@Jura Could you please update the portal with the latest files. We need to add 2017 to the visualization. 

https://www.dropbox.com/sh/kvy7lopqrasvnis/AAAwq091C2-8dY8OkSdWLdXTa?dl=0

**Comment by Jura** [comment]
@abdulriza what should be the timestamp for this update? January 31?

**Comment by abdulriza** [comment]
@Jura Yes. January 31st 2017. Please make sure that the 2016 xml is replaced with the new one while we add the 2017 one.
