### ISSUE TITLE
March portal update

### ISSUE THREAD

**Issue by abdulriza** [undp/undp.github.com#216]
@Jura Could you please update the portal with the latest data (as of 31st March);

https://www.dropbox.com/sh/kvy7lopqrasvnis/AAAwq091C2-8dY8OkSdWLdXTa?dl=0

Thanks.

**Comment by Jura** [comment]
Hi Riza,
please check the numbers and let me know
![image](https://cloud.githubusercontent.com/assets/417604/25092902/ccb70bf2-235d-11e7-9755-1704b8c90445.png)

**Comment by abdulriza** [comment]
@Jura Numbers look perfect. We can push it live. Thanks.

**Comment by abdulriza** [comment]
@Jura There is an urgent request from RBAS to take out all the documents for the project 00044201 due to donor request citing the donor agreement clause not to publish any information. I have prepared the  new xml with the required changes and I would appreciate if you could update the portal accordingly. The numbers will not change after the update but the documents (except procurement notices) should be gone for http://open.undp.org/#project/00044201

https://www.dropbox.com/sh/kvy7lopqrasvnis/AAAwq091C2-8dY8OkSdWLdXTa?dl=0

Thanks.

**Comment by abdulriza** [comment]
Perfect. Thanks Jura.
