### ISSUE TITLE
bug on regional office SVK

### ISSUE THREAD

**Issue by akshaysinha** [undp/undp.github.com#22]
Hi Nate,
The regional offices map deactivation is working great now, thank you for making that fix! 
One quick thing there is still one regional office left that has a map as per below, could you deactivate it similarly. Thank you!
http://developmentseed.org/undp-projects/#2012/filter/operating_unit-SVK

**Comment by smit1678** [comment]
@abdulriza is this still an issue?

**Comment by abdulriza** [comment]
@smit1678 This is no more an issue. This regional office is closed. I am closing this ticket. Thanks.
