### ISSUE TITLE
PO data update

### ISSUE THREAD

**Issue by abdulriza** [undp/undp.github.com#220]
@Jura Could we please update the portal with the latest PO data updates. 

https://www.dropbox.com/sh/nxq93hyajzqyrkk/AADYI_UDX5VDMJwsnYgEdzR3a?dl=0

Thanks.

**Comment by Jura** [comment]
Acknowledged. Will do in a coming days.

**Comment by Jura** [comment]
Hi @abdulriza , field PO_DESCRIPTION is missing in the table provided, please update and resubmit

**Comment by abdulriza** [comment]
@Jura Thanks for pointing it out. I should have noticed. The file is now updated with po_description field.
