### ISSUE TITLE
Donor data update

### ISSUE THREAD

**Issue by abdulriza** [undp/undp.github.com#221]
@Jura Here is 2016 final donor contribution data for portal update. 

https://www.dropbox.com/sh/1brkujszuvu8aoz/AACo0DMnaQnrqJHrjXMlSfDXa?dl=0

As discussed, I have included new value of 'Other" in the Fund Rollup Level 3 column in fund_modalities csv file, which will require code modification in order to be added to the existing table as a new Non-core modality type. 

We will also change the time stamp for both sections (Regular resources and Non-core) to 2016.

Thanks.

**Comment by Jura** [comment]
@abdulriza , is it ok that overall amount of lines in fund_modalities.csv went down from 5877 to 943?

**Comment by abdulriza** [comment]
@Jura it should be fine. The file is now aggregated at fund roll-up level per donor and therefore consolidated in lesser number of lines.

**Comment by Jura** [comment]
And what should be the new label? I mean instead of "Contributions to Regular Resources as of December 31, 2015"

**Comment by abdulriza** [comment]
We will only change 2015 to 2016.
