### ISSUE TITLE
Portal update - as of 30th April 2017

### ISSUE THREAD

**Issue by abdulriza** [undp/undp.github.com#225]
@Jura here is the latest files for the portal update. 

https://www.dropbox.com/sh/kvy7lopqrasvnis/AAAwq091C2-8dY8OkSdWLdXTa?dl=0

Once it is updated the portal should show the total budget 4,936.07M and total expenditure of 992.09M.

Thanks.

**Comment by abdulriza** [comment]
@Jura Could you please re-run the update with the xml file in the same location. 

https://www.dropbox.com/sh/kvy7lopqrasvnis/AAAwq091C2-8dY8OkSdWLdXTa?dl=0

There is one urgent request to remove a document and I have modified the xml accordingly. Therefore, once updated there shouldn't be any changes in financial but the prodoc document for project 00093319 wil not be appearing on the document list.

Thanks

**Comment by Jura** [comment]
No problem, I'll have a look at it. 
BTW, if you would need such a change immediately in the feature you can just manually update respective .json file (https://github.com/undp/open.undp.org/blob/gh-pages/api/projects/00093319.json). Just make sure the syntax of remaining code is correct
