### ISSUE TITLE
PO information showing consultant names

### ISSUE THREAD

**Issue by abdulriza** [undp/undp.github.com#227]
@Jura In presenting PO details we replace the vendor names of those under vendor class 'SSA / IC / RLA'  replaced by 'consultant'. It appears that this is not working. For example; http://open.undp.org/#project/00080732 shows all consultant names who are under 'SSA / IC / RLA' vendor class. 

Could you please have a look. Thanks.

**Comment by Jura** [comment]
@abdulriza as of current setup only vendors marked as "SSA / IC" or "Service contract" are masked as generic "Consultant". "SSA / IC / RLA"  is not accounted for, should I add it to the list? Here is the current map for your reference:

```
"Beneficiary Family": "Individual",
"Fellow": "Individual",
"Meeting Participant" : "Individual", 
"Service Contract": "Consultant",
"SSA / IC": "Consultant",
"Staff": "Individual",
"UNV": "UNV"
```

**Comment by abdulriza** [comment]
@Jura Thanks. Not sure if they renamed the category in Atlas lately or I made the mistake initially but the correct value is "SSA / IC / RLA". Could we replace "SSA / IC" to "SSA / IC / RLA" in the mapping? 

Thanks.
