### ISSUE TITLE
Change of CC licence type on about us page

### ISSUE THREAD

**Issue by abdulriza** [undp/undp.github.com#232]
@Jura After the discussion with LO we have decided to change the Creative Commons License type to CC-BY to CC BY 3.0 IGO) which will still allow the free use without additional limitation but covers the resolution of disputes clause in accordance with UNDP's privileges and immunities. Therefore, could we change the license texts appear on about us - using open.undp.org page (http://open.undp.org/#about/usage) as;

        Creative Commons’ Attribution 3.0 IGO License (CC-BY 3.0 IGO). 

The link provided to the texts is also broken. Can you please replace the link with;

       http://iatistandard.org/203/guidance/how-to-publish/licensing/

**Comment by Jura** [comment]
I also fixed Download popup
