### ISSUE TITLE
New focus areas

### ISSUE THREAD

**Issue by smit1678** [undp/undp.github.com#53]
@abdulriza Do you have a list of the new focus areas?

**Comment by smit1678** [comment]
@scisco Reopening this. Ran the new script from `iati` branch and all focus_areas in the project summary.json are null: 

![](https://api.monosnap.com/image/download?id=wppECoWx9Rr0vS44CzXX6YP6SB6HoR)

This seems to be due to the fact that the new xml does not include a code in the element, only text: 

```
<sector vocabulary="RO">Responsive Institutions</sector>
```

@abdulriza Is this the new standard? Previous versions were including a `code` in the element:

```
<sector vocabulary="RO" code="4">Environment &amp; sustainable development</sector>
```

**Comment by abdulriza** [comment]
@smit1678 @scisco the numbers shown in previous version for this were not really a code list but sequence numbers. Therefore, the codes got omitted with the new system. If you think it is important we can include it. Let me know.

**Comment by smit1678** [comment]
@abdulriza let's include it to keep in line with the existing code. Send us an updated xml when it's ready.

**Comment by abdulriza** [comment]
@smit1678. Sure. I will share the data by tomorrow. 

Thanks.

**Comment by smit1678** [comment]
@abdulriza Were you able to make any progress on the new file?

**Comment by abdulriza** [comment]
@smit1678 had some issues in getting the updated files. I have shared the new files in basecamp now. Thanks.
